### ISSUE TITLE
Design Interview Page

### ISSUE THREAD

**Issue by to-Gabriel** [csusmGDSC/website#20]
##Interview Page
This page introduces the interview team (leetcode)

###Data Structures & Algorithms
###Mock Interviews
### Leetcode & HackerRank

Each topic should have a respective description and any necessary resources accessible to user.

**Comment by to-Gabriel** [comment]
Hey @joshlaraa this could be a cool design to possibly take after https://about.google/commitments/#protecting_users its similar to what we discussed except instead of tabs with subpages, the toolbar reroutes to break points in the page

**Comment by joshlaraa** [comment]
Hey @to-Gabriel, interview page is up and running!

**Comment by to-Gabriel** [comment]
Well done, lets work out some of those spacing quirks and see what UX features we can implement to make things as smooth as possible
