### ISSUE TITLE
Interview Page Update

### ISSUE THREAD

**Issue by JaedonSpurlock01** [csusmGDSC/website#50]
Remove the interview page since it introduces complexity

Here's what we'll do instead

- Add tags feature to event object
- Add markdown support to have code samples, youtube embeds, links, images, and more
- Replace the quill editor with markdown editor

**Comment by to-Gabriel** [comment]
We'll be adding this functionality in to the event details page itself.

This will remove the need for creating a separate tab.

1. Add a category to each event
2. Add sort by category
3. Implement above features in event detail given event is of type "Leet Code Session"

**Comment by JaedonSpurlock01** [comment]
@to-Gabriel If you're working on this, you're welcome to add the sorting features inside of /app/events/page.tsx, I am currently refactoring the create-event to cover the new features. The tags will be under eventData.tags.
